// Map of emoji → local Fluent-3D asset key (files live in /public/emoji3d/<key>.png).
// Any emoji not listed here (or whose asset fails to load) renders as the plain
// emoji via the <Icon3D> fallback — so this map can grow safely over time.
export const EMOJI_3D = {
  '📋': 'clipboard',
  '❌': 'cross_mark',
  '🗑': 'wastebasket',
  '📄': 'page_facing_up',
  '🙈': 'see_no_evil',
  '🔒': 'locked',
  '🔎': 'magnifying_right',
  '🔊': 'speaker',
  '📥': 'inbox_tray',
  '👁': 'eye',
  '✅': 'check_mark_button',
  '🧠': 'brain',
  '🙂': 'slightly_smiling',
  '😶': 'face_without_mouth',
  '😎': 'sunglasses',
  '😅': 'sweat_smile',
  '🗂': 'card_index',
  '🔐': 'locked_with_key',
  '🔍': 'magnifying_left',
  '📸': 'camera_flash',
  '📷': 'camera',
  '📚': 'books',
  '📖': 'open_book',
  '📊': 'bar_chart',
  '🃏': 'joker',
  '✏': 'pencil',
  '☁': 'cloud',
  '⚠': 'warning',
  '🚀': 'rocket',
  '🎉': 'party',
  '🎯': 'bullseye',
  '⌨': 'keyboard',
  '⏹': 'stop_button',
};
