// Local quote bank — no external API (reliable, offline, corporate-network safe).
// Used by the Vault: a random quote on each visit, auto-rotating every minute.
export const QUOTES = [
  { text: 'The beautiful thing about learning is that no one can take it away from you.', author: 'B.B. King' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Success is the sum of small efforts repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Develop a passion for learning. If you do, you will never cease to grow.', author: 'Anthony J. D’Angelo' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
  { text: 'Strive for progress, not perfection.', author: 'Unknown' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'The roots of education are bitter, but the fruit is sweet.', author: 'Aristotle' },
  { text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Procrastination makes easy things hard and hard things harder.', author: 'Mason Cooley' },
  { text: 'Don’t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'You don’t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'A little progress each day adds up to big results.', author: 'Unknown' },
  { text: 'Knowledge is power. Information is liberating.', author: 'Kofi Annan' },
  { text: 'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.', author: 'Brian Herbert' },
  { text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown' },
  { text: 'Great things never came from comfort zones.', author: 'Unknown' },
  { text: 'Doubt kills more dreams than failure ever will.', author: 'Suzy Kassem' },
  { text: 'Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.', author: 'Abigail Adams' },
  { text: 'Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.', author: 'Richard Feynman' },
  { text: 'I have not failed. I’ve just found 10,000 ways that won’t work.', author: 'Thomas Edison' },
  { text: 'The more that you read, the more things you will know.', author: 'Dr. Seuss' },
  { text: 'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', author: 'Albert Einstein' },
  { text: 'Anyone who stops learning is old, whether at twenty or eighty.', author: 'Henry Ford' },
  { text: 'Today a reader, tomorrow a leader.', author: 'Margaret Fuller' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Dreams don’t work unless you do.', author: 'John C. Maxwell' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Continuous improvement is better than delayed perfection.', author: 'Mark Twain' },
  { text: 'The future belongs to those who learn more skills and combine them in creative ways.', author: 'Robert Greene' },
  { text: 'Learning is a treasure that will follow its owner everywhere.', author: 'Chinese Proverb' },
  { text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Excellence is not a skill, it’s an attitude.', author: 'Ralph Marston' },
  { text: 'The harder you work for something, the greater you’ll feel when you achieve it.', author: 'Unknown' },
  { text: 'Repetition is the mother of learning, the father of action, the architect of accomplishment.', author: 'Zig Ziglar' },
  { text: 'Small daily improvements over time lead to stunning results.', author: 'Robin Sharma' },
  { text: 'Memory is the treasury and guardian of all things.', author: 'Cicero' },
  { text: 'Tell me and I forget, teach me and I may remember, involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'The whole purpose of education is to turn mirrors into windows.', author: 'Sydney J. Harris' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'Curiosity is the wick in the candle of learning.', author: 'William Arthur Ward' },
  { text: 'What we learn with pleasure we never forget.', author: 'Alfred Mercier' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'Your education is a dress rehearsal for a life that is yours to lead.', author: 'Nora Ephron' },
];

// A random quote from the bank.
export const randomQuote = () => QUOTES[Math.floor(Math.random() * QUOTES.length)];
